### ISSUE TITLE
Why not take the last argument of lambda function of deal.ensure as a return of the function?

### ISSUE THREAD

**Issue by KUR-creative** [life4/deal#41]
```python
@deal.ensure(lambda a, result: a + 1 == result) # 1) working
#@deal.ensure(lambda a, ret: a == ret + 1) # 2) not working
def example(a):
    ret = a + 1
    return ret

example(1)
```
In case of 2)
```
Traceback (most recent call last):
  File "play_deal.py", line 33, in <module>
    example(1)
  File "/home/kur/.local/lib/python3.7/site-packages/deal/_decorators/base.py", line 86, in wrapped
    return self.patched_function(*args, **kwargs)
  File "/home/kur/.local/lib/python3.7/site-packages/deal/_decorators/ensure.py", line 19, in patched_function
    self.validate(*args, result=result, **kwargs)
  File "/home/kur/.local/lib/python3.7/site-packages/deal/_decorators/base.py", line 36, in validate
    self._simple_validation(*args, **kwargs)
  File "/home/kur/.local/lib/python3.7/site-packages/deal/_decorators/base.py", line 60, in _simple_validation
    validation_result = self.validator(*args, **kwargs)
TypeError: <lambda>() got an unexpected keyword argument 'result'
```
Why last arguments of @deal.ensure must be `result`?
I think return value can be just last argument of the lambda function and then argument could be arbitrary named..

**Comment by orsinium** [comment]
Then if you pass a keyword argument into function itself, it will fail because the calling of the function will look like this:

```python
contract(a=a, result)  # SyntaxError
```

**Comment by KUR-creative** [comment]
Aha, that make sense. I'll close this issue. Sorry for bothering.

**Comment by orsinium** [comment]
You're welcome :)
